In [8]:
path = r"C:\Users\Mykola\Downloads\entities.ftm.json"

In [5]:
import pandas as pd
df = pd.read_csv(r"C:\OTP Draft\kved_01.11(1-5).csv", dtype={"EDRPOU_CODE":"str"})
df

,SECTION_CODE,SECTION_NAME,CHAPTER_CODE,CHAPTER_NAME,GROUP_CODE,GROUP_NAME,CLASS_CODE,CLASS_NAME,EDRPOU_CODE,JUR_PER_NAME,...,ACTIVITES,CONTACT_INFO,Відомості про органи управління юридичної особи,Частка держави в підприємстві згідно з реєстром Фонду держмайна України,Перелік засновників/учасників юридичної особи,"Відомості про строк, визначений засновниками (учасниками) юридичної особи, судом або органом, що прийняв рішення про припинення юридичної особи, для заявлення кредиторами своїх вимог","Дата та номер запису про державну реєстрацію припинення юридичної особи, підстава для його внесення",Кінцевий бенефіціарний власник (контролер),"Інформація про кінцевого бенефіціарного власника (контролера) юридичної особи, у тому числі кінцевого бенефіціарного власника (контролера) її засновника, якщо засновник - юридична особа: прізвище, ім’я, по батькові (за наявності), країна громадянства, місце проживання, а також повне найменування та ідентифікаційний код (для резидента) засновника юридичної особи, в якому ця особа є кінцевим бенефіціарним власником (контролером), або інформація про відсутність кінцевого бенефіціарного власника (контролера) юридичної особи, у тому числі кінцевого бенефіціарного власника (контролера) її засновника",Дані про перебування юридичної особи в процесі припинення
0,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22215409,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО АЛІ-92,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **0...","ЗАГАЛЬНІ ЗБОРИ ЧЛЕНІВ ФГ, ГОЛОВА ФГ",0,ІВАХНЮК АЛЛА ЛЕОНІДІВНА Адреса засновника: Укр...,NaN,NaN,NaN,NaN,NaN
1,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22215528,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО НАДІЯ,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **1...",ЧЛЕН ФГ,0,ПІЦЕНКО МИХАЙЛО ЯКОВИЧ Адреса засновника: Укра...,09.08.2015,Дата запису: 18.09.2015 Номер запису: 1 445 11...,NaN,NaN,NaN
2,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22215540,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО НАТАЛКА,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **6...",ЗАСНОВНИК,0,ВОЛИНЕЦЬ ОЛЕКСІЙ СЕРГІЙОВИЧ Адреса засновника:...,NaN,Дата запису: 11.04.2023 Номер запису: 1 004 45...,ВОЛИНЕЦЬ ОЛЕКСІЙ СЕРГІЙОВИЧ Адреса засновника:...,NaN,NaN
3,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22215563,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО СИДОРОВО,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **4...",ГОЛОВА СФГ,0,СІДОРОВ МИКОЛА ТИМОФІЙОВИЧ Адреса засновника: ...,NaN,NaN,NaN,NaN,NaN
4,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",24436825,СТИМУЛ-ІІ,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **3...",ГОЛОВА СФГ,0,БОЙКО СЕРГІЙ СЕРГІЙОВИЧ Адреса засновника: Укр...,NaN,NaN,КІНЦЕВИМ БОЙКО СЕРГІЙ СЕРГІЙОВИЧ Адреса заснов...,NaN,NaN
5,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216166,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО ДЖЕРЕЛО-2,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **1...",Загальні збори членів господарства; Голова гос...,0,Баранець Галина Олексіївна Адреса засновника: ...,NaN,NaN,NaN,"Баранець Костянтин Сергійович Україна, 28001, ...",NaN
6,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216219,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО ПРОЛІСОК,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **0...",ГОЛОВА ФГ,0,ВЕРХЛОМЧУК РАЇСА ГРИГОРІВНА Адреса засновника:...,NaN,NaN,NaN,NaN,NaN
7,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216226,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО НИВА-Г,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **3...",ЗАГАЛЬНІ ЗБОРИ ЧЛЕНІВ ФГ,0,ЄЛЕЦЬКА ТЕТЯНА ВІКТОРІВНА Адреса засновника: У...,NaN,NaN,NaN,NaN,NaN
8,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216373,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО БАЛІЦЬКОГО ВАСИЛЯ ІВАН...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **3...",ВИЩЩИЙ-ЗАГАЛЬНІ ЗБОРИ;ВИКОНАВЧИЙ-ГОЛОВА ФГ.,0,ГОЛЮЧИК ЛЮБОВ ВАСИЛІВНА Адреса засновника: Укр...,NaN,NaN,NaN,"ГОЛЮЧИК ЛЮБОВ ВАСИЛІВНА Україна, 25006, Кірово...",NaN
9,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216383,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО ДЯЧЕНКА ІГОРЯ МИКОЛАЙО...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **2...",ГОЛОВА СФГ,0,ДЯЧЕНКО ІГОР МИКОЛАЙОВИЧ Адреса засновника: Ук...,NaN,NaN,NaN,"Дяченко Ігор Миколайович Україна, 26112, Кіров...",NaN
10,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216404,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО ЧЕПКОГО ВОЛОДИМИРА ПАВ...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **2...",Загальні збори; Голова,0,ЧЕПКИЙ ВОЛОДИМИР ПАВЛОВИЧ Адреса засновника: У...,NaN,NaN,NaN,"ЧЕПКА ОЛЕНА ВОЛОДИМИРІВНА Україна, 20301, Черк...",NaN
11,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216410,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО КОВАЛЯ ВІТАЛІЯ ПЕТРОВИЧА,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **2...",ВИЩИЙ-ЗАГАЛЬНІ ЗБОРИ;ВИКОНАВЧИЙ-ГОЛОВА ФГ.,0,КОВАЛЬ ІННА ВІТАЛІЇВНА Адреса засновника: Укра...,NaN,NaN,NaN,"Коваль Інна Віталіївна Україна, 20300, Черкась...",NaN
12,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216433,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО КРАВЧЕНКА МИКОЛИ ОЛЕКС...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **2...",Загальні збори; Голова ФГ,0,КРАВЧЕНКО МИКОЛА ОЛЕКСІЙОВИЧ Адреса засновника...,NaN,NaN,NaN,"Кравченко Микола Олексійович Україна, 26111, К...",NaN
13,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216456,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО ПОДОЛЯНА ВІКТОРА ПЕТРО...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **2...",Загальні збори; Голова ФГ,0,ПОДОЛЯН ВІКТОР ПЕТРОВИЧ Адреса засновника: Укр...,NaN,NaN,NaN,"Подолян Віктор Петрович Україна, 26100, Кірово...",NaN
14,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216545,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО МОМОТА ПЕТРА ОЛЕКСІЙОВИЧА,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, Кір...",ВИЩИЙ-ЗАГАЛЬНІ ЗБОРИ;ВИКОНАВЧИЙ - ГОЛОВА ФГ,0,МОМОТ РУСЛАН ПЕТРОВИЧ Адреса засновника: Украї...,NaN,NaN,NaN,"МОМОТ РУСЛАН ПЕТРОВИЧ Україна, Кіровоградська ...",NaN
15,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216568,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО ГЛИНСЬКОГО ПЕТРА ПАВЛО...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **3...",засновник; голова,0,ГЛИНСЬКИЙ ПЕТРО ПАВЛОВИЧ Адреса засновника: Ук...,NaN,NaN,NaN,"Глинський Петро Павлович Україна, 47201, Терно...",NaN
16,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216574,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО БАНАДИГИ ПЕТРА ФЕДОРОВИЧА,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **3...",засновник; голова,0,БАНАДИГА ПЕТРО ФЕДОРОВИЧ Адреса засновника: Ук...,NaN,NaN,NaN,"Банадига Петро Федорович Україна, 26153, Кіров...",NaN
17,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",24437581,СЕЛЯНСЬКЕ (ФЕРМЕРСЬКЕ) ГОСПОДАРСТВО ЗОРЯ,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **0...",ГОЛОВА ПРАВЛІННЯ,0,ПІДДУБНИЙ ВОЛОДИМИР МИКОЛАЙОВИЧ Адреса засновн...,NaN,NaN,NaN,"Піддубний Володимир Миколайович Україна, 52400...",NaN
18,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216580,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО МЕРЗЕСКУЛА МИКОЛИ ПАНТ...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **1...","ВИЩИЙ-ЗАГАЛЬНІ ЗБОРИ, ВИКОНАВЧИЙ-ГОЛОВА ФГ.",0,МЕРЗЕСКУЛ СЕРГІЙ МИКОЛАЙОВИЧ Адреса засновника...,NaN,NaN,NaN,"Мерзескул Сергій Миколайович Україна, 20523, Ч...",NaN
19,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22216628,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО КРАВЧЕНКА АНДРІЯ ОЛЕКС...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **2...",Загальні збори; Голова ФГ,0,КРАВЧЕНКО АНДРІЙ ОЛЕКСІЙОВИЧ Адреса засновника...,NaN,NaN,NaN,"КРАВЧЕНКО АНДРІЙ ОЛЕКСІЙОВИЧ Україна, 09100, К...",NaN
20,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",30926857,ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ СІЛЬСЬ...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **4...",ЗАГАЛЬНІ ЗБОРИ,0,ЛУК'ЯНОВА ОЛЕКСАНДРА ВАДИМІВНА Адреса засновни...,NaN,NaN,NaN,NaN,NaN
21,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",32418393,СЕЛЯНСЬКЕ ( ФЕРМЕРСЬКЕ ) ГОСПОДАРСТВО КОРДОН,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **0...",ГОЛОВА СФГ,0,УСЕНКО АНДРІЙ СЕРГІЙОВИЧ Адреса засновника: Ук...,04.11.2018,NaN,NaN,NaN,04.09.2018 - в стані припинення 10021100011000...
22,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",32418409,СЕЛЯНСЬКЕ (ФЕРМЕРСЬКЕ) ГОСПОДАРСТВО ТИТАНІК,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **1...",NaN,0,КАБАНОВ РУСЛАН ВАСИЛЬОВИЧ Адреса засновника: У...,NaN,NaN,NaN,"КАБАНОВ РУСЛАН ВАСИЛЬОВИЧ Україна, 19801, Черк...",NaN
23,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",22219325,НАЦІОНАЛЬНА АГРАРНО-ПРОМИСЛОВА ТОРГІВЕЛЬНА КОМ...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **0...",ЗАГАЛЬНІ ЗБОРИ,0,ШВЕЦЬ ГРИГОРІЙ ГРИГОРОВИЧ Адреса засновника: С...,NaN,Дата запису: 11.03.2015 Номер запису: 1 446 11...,NaN,NaN,NaN
24,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",32418423,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО КОЗАЦЬКИЙ ШЛЯХ,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **4...",NaN,0,СЕМИНОГА ВОЛОДИМИР ІВАНОВИЧ Адреса засновника:...,NaN,NaN,NaN,"Семинога Володимир Іванович Україна, 08129, Ки...",NaN
25,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",24440293,СЕЛЯНСЬКЕ ( ФЕРМЕРСЬКЕ) ГОСПОДАРСТВО ЧАЙКА,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **0...",ГОЛОВА СФГ,0,СІДЕЛЬНИКОВА МАРИНА АНАТОЛІЇВНА Адреса засновн...,NaN,NaN,NaN,NaN,NaN
26,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",32418440,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО СОНЯЧНЕ,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **3...",NaN,0,КОШИК ЛЮБОВ МИКОЛАЇВНА Адреса засновника: Укра...,NaN,NaN,NaN,NaN,NaN
27,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",32418456,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО БОРИСФЕН,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **1...",СЕЛЯНСЬКІ/ ФЕРМЕРСЬКІ/ ГОСПОДАРСТВА УКРАЇНИ,0,Золотоверхий Віктор Борисович Адреса засновник...,NaN,NaN,NaN,"Золотоверхий Віктор Борисович Україна, 20701, ...",NaN
28,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",32418461,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО АГРАРІЙ,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **3...",ГОЛОВА СФГ,0,БЯЛКІВСЬКИЙ ВАСИЛЬ ДОРОФІЙОВИЧ Адреса засновни...,NaN,NaN,NaN,"БЯЛКІВСЬКИЙ ВАСИЛЬ ДОРОФІЙОВИЧ Україна, 20753,...",NaN
29,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",32418498,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО СТАРТ,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **0...",ГОЛОВА СФГ,0,ШТАНЧЕНКО ВІКТОР ІВАНОВИЧ Адреса засновника: У...,NaN,NaN,І,NaN,NaN
30,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",24440494,СЕЛЯНСЬКЕ (ФЕРМЕРСЬКЕ) ГОСПОДАРСТВО АЛТЕЙ,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **3...",NaN,0,МЕХЕДЬКО ОЛЕКСАНДР БОРИСОВИЧ Адреса засновника...,NaN,NaN,NaN,NaN,NaN
31,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",30927117,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО СЕЛЯНСЬКЕ (ФЕРМЕРСЬКЕ)...,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: 52950, Дніпр...",NaN,0,ПІНЧУК ПЕТРО ГРИГОРОВИЧ Адреса засновника: 529...,NaN,NaN,NaN,NaN,31.10.2014 - в стані припинення Підстава: за с...
32,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",32418592,ПРИВАТНЕ ПІДПРИЄМСТВО ЛАКТУС,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **2...",ДИРЕКТОР,0,СТУКАЛ ПАВЛО МИКОЛАЙОВИЧ Адреса засновника: Ук...,NaN,NaN,NaN,"Стукал Павло Миколайович Україна, 84022, Донец...",NaN
33,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",30927172,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО СЕЛЯНСЬКЕ ФЕРМЕРСЬКЕ Г...,...,Основний: 01.11 Вирощування зернових та техніч...,"Місцезнаходження юридичної особи: 52940, , С.К...",ГОЛОВА СФГ,0,ЛЕОНОВ ОЛЕКСАНДР ВІКТОРОВИЧ Адреса засновника:...,NaN,Дата запису: 24.02.2005 Номер запису: 1 207 13...,NaN,NaN,NaN
34,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",33915979,ФЕРМЕРСЬКЕ ГОСПОДАРСТВО САДИБА ПЛЮС,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **2...",ГОЛОВА СФГ,0,ІВАНЮК ПЕТРО ЯРОСЛАВОВИЧ Адреса засновника: Ук...,11.02.2014,Дата запису: 16.03.2017 Номер запису: 1 592 11...,NaN,NaN,NaN
35,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",30927185,СЕЛЯНСЬКЕ (ФЕРМЕРСЬКЕ) ГОСПОДАРСТВО ХЛІБОРОБ,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **0...",NaN,0,ГРИЖЕНКО СЕРГІЙ МИКОЛАЙОВИЧ Адреса засновника:...,NaN,NaN,NaN,NaN,NaN
36,A,"СІЛЬСЬКЕ ГОСПОДАРСТВО, ЛІСОВЕ ГОСПОДАРСТВО ТА ...",1,"Сільське господарство, мисливство та надання п...",1.1,ВИРОЩУВАННЯ ОДНОРІЧНИХ І ДВОРІЧНИХ КУЛЬТУР,1.11,"Вирощування зернових культур (крім рису), бобо...",30927206,СЕЛЯНСЬКЕ (ФЕРМЕРСЬКЕ) ГОСПОДАРСТВО НОВАТОР,...,Основний: 01.11 Вирощування зернових культур (...,"Місцезнаходження юридичної особи: Україна, **2...",Рішення засновника,0,ГНІЛОВ ОЛЕКСАНДР МИКОЛАЙОВИЧ Адреса засновника...,NaN,NaN,NaN,"Гнілов Олександр Миколайович Україна, 52950, Д...",NaN

In [6]:
df["EDRPOU_CODE"].to_csv("data_for test.csv", index=False)

In [9]:
import json
import pandas as pd

rows = []

with open(path, 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        obj = json.loads(line)
        props = obj.get("properties", {})

        row = {
            "id": obj.get("id"),
            "name": props.get("name", [None])[0],
            "edrpou": props.get("registrationNumber", [None])[0],
            "address": props.get("address", [None])[0],
            "status": props.get("status", [None])[0],
        }

        rows.append(row)

        if i >= 1000:  # для тесту
            break

df = pd.DataFrame(rows)
df.head()

,id,name,edrpou,address,status
0,ua-edr-00000000-25402709caa92c7085b77454e08ef0...,"ВАТ ""ІЛЛІНЕЦЬКЕ РП ""АГРОМАШ""""",00000000,"Україна, 22700, Вінницька обл., Іллінецький р-...",припинено
1,ua-edr-00000000-6ce941d503b62b3682065252a14965...,"ЗАКРИТЕ АКЦІОНЕРНЕ ТОВАРИСТВО ""МАНА""",00000000,"Україна, 69124, ВУЛ.РУБАНА, БУД.7 А, КВ.132, М...",припинено
2,ua-edr-00000000-7c983582f0a684366459048f0bbff9...,"ГО ""ЛОО ФМСУ""",00000000,"Україна, 79035, ПАСІЧНА, 141, ЛЬВІВ, СИХІВСЬКИ...",зареєстровано
3,ua-edr-00000000-a79007386305d18608551ea4886c43...,"ПРИВАТНЕ ПІДПРИЄМСТВО ""ЗАРКО""",00000000,"Україна, 82400, ВУЛ. ЧАЙКОВСЬКОГО, 4, 7, М. СТ...",припинено
4,ua-edr-00000000-a7ad710f7c20228c6bfe7d7f7ebbc9...,"ОМГО ""УСВА""",00000000,"Україна, 42700, Сумська обл., місто Охтирка, В...",припинено

In [10]:
import json
import pandas as pd

path = r"C:\Users\Mykola\Downloads\senzing.json"

def fix_text(s):
    if s is None:
        return None
    try:
        return s.encode('latin1').decode('utf-8')
    except:
        return s

rows = []

with open(path, 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        obj = json.loads(line)

        # --- name ---
        names = obj.get("NAMES", [])
        name = None
        for n in names:
            if n.get("NAME_TYPE") == "PRIMARY":
                name = fix_text(n.get("NAME_ORG"))
                break

        # --- address ---
        addresses = obj.get("ADDRESSES", [])
        address = fix_text(addresses[0]["ADDR_FULL"]) if addresses else None

        # --- edrpou ---
        identifiers = obj.get("IDENTIFIERS", [])
        edrpou = None
        for ident in identifiers:
            if "NATIONAL_ID_NUMBER" in ident:
                edrpou = ident["NATIONAL_ID_NUMBER"]
                break

        rows.append({
            "id": obj.get("RECORD_ID"),
            "name": name,
            "address": address,
            "edrpou": edrpou
        })

        if i >= 1000:
            break

df = pd.DataFrame(rows)
df.head()

,id,name,address,edrpou
0,ua-edr-00000000-25402709caa92c7085b77454e08ef0...,"ВАТ ""ІЛЛІНЕЦЬКЕ РП ""АГРОМАШ""""","Україна, 22700, Вінницька обл., Іллінецький р-...",00000000
1,ua-edr-00000000-6ce941d503b62b3682065252a14965...,"ЗАКРИТЕ АКЦІОНЕРНЕ ТОВАРИСТВО ""МАНА""","Україна, 69124, ВУЛ.РУБАНА, БУД.7 А, КВ.132, М...",00000000
2,ua-edr-00000000-7c983582f0a684366459048f0bbff9...,"ГО ""ЛОО ФМСУ""","Україна, 79035, ПАСІЧНА, 141, ЛЬВІВ, СИХІВСЬКИ...",00000000
3,ua-edr-00000000-a79007386305d18608551ea4886c43...,"ПРИВАТНЕ ПІДПРИЄМСТВО ""ЗАРКО""","Україна, 82400, ВУЛ. ЧАЙКОВСЬКОГО, 4, 7, М. СТ...",00000000
4,ua-edr-00000000-a7ad710f7c20228c6bfe7d7f7ebbc9...,"ОМГО ""УСВА""","Україна, 42700, Сумська обл., місто Охтирка, В...",00000000